name: Terraform Azure Databricks Deployment

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Adjust version if needed

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform deployment
      run: terraform plan

    - name: Apply Terraform changes
      run: terraform apply -auto-approve

    - name: Save Terraform state
      run: terraform state pull > terraform.tfstate

    # Add additional steps as needed, such as running tests or notifying stakeholders
